// Place fonts/Madness.ttf in your fonts/ directory and
// add the following to your pubspec.yaml
// flutter:
//   fonts:
//    - family: Madness
//      fonts:
//       - asset: fonts/Madness.ttf
import 'package:flutter/widgets.dart';

class Madness {
  Madness._();

  static const String _fontFamily = 'Madness';

  static const IconData lock_1_svgrepo_com = IconData(0xea996, fontFamily: _fontFamily);
  static const IconData restart_square_svgrepo_com = IconData(0xea995, fontFamily: _fontFamily);
  static const IconData restart_circle_svgrepo_com = IconData(0xea994, fontFamily: _fontFamily);
  static const IconData power_svgrepo_com = IconData(0xea993, fontFamily: _fontFamily);
  static const IconData pin_circle_svgrepo_com = IconData(0xea992, fontFamily: _fontFamily);
  static const IconData logout_2_svgrepo_com = IconData(0xea991, fontFamily: _fontFamily);
  static const IconData key_minimalistic_square_svgrepo_com = IconData(0xea990, fontFamily: _fontFamily);
  static const IconData cloudy_moon_svgrepo_com = IconData(0xea989, fontFamily: _fontFamily);
  static const IconData cloud_waterdrop_svgrepo_com = IconData(0xea988, fontFamily: _fontFamily);
  static const IconData cloud_svgrepo_com = IconData(0xea987, fontFamily: _fontFamily);
  static const IconData cloud_sun_svgrepo_com = IconData(0xea986, fontFamily: _fontFamily);
  static const IconData cloud_sun_2_svgrepo_com = IconData(0xea985, fontFamily: _fontFamily);
  static const IconData cloud_storm_svgrepo_com = IconData(0xea984, fontFamily: _fontFamily);
  static const IconData cloud_storage_svgrepo_com = IconData(0xea983, fontFamily: _fontFamily);
  static const IconData clouds_svgrepo_com = IconData(0xea982, fontFamily: _fontFamily);
  static const IconData cloud_snowfall_svgrepo_com = IconData(0xea981, fontFamily: _fontFamily);
  static const IconData cloud_snowfall_minimalistic_svgrepo_com = IconData(0xea980, fontFamily: _fontFamily);
  static const IconData cloud_rain_svgrepo_com = IconData(0xea979, fontFamily: _fontFamily);
  static const IconData cloud_bolt_svgrepo_com = IconData(0xea978, fontFamily: _fontFamily);
  static const IconData bolt_circle_svgrepo_com = IconData(0xea977, fontFamily: _fontFamily);
  static const IconData clock1 = IconData(0xea976, fontFamily: _fontFamily);
  static const IconData spotify = IconData(0xea975, fontFamily: _fontFamily);
  static const IconData linux = IconData(0xea974, fontFamily: _fontFamily);
  static const IconData globe = IconData(0xea973, fontFamily: _fontFamily);
  static const IconData gitlab = IconData(0xea972, fontFamily: _fontFamily);
  static const IconData github2 = IconData(0xea969, fontFamily: _fontFamily);
  static const IconData dev2 = IconData(0xea971, fontFamily: _fontFamily);
  static const IconData android = IconData(0xea970, fontFamily: _fontFamily);
  static const IconData github = IconData(0xea968, fontFamily: _fontFamily);
  static const IconData electricity = IconData(0xea967, fontFamily: _fontFamily);
  static const IconData box_time = IconData(0xea966, fontFamily: _fontFamily);
  static const IconData box_tick = IconData(0xea965, fontFamily: _fontFamily);
  static const IconData moon = IconData(0xea964, fontFamily: _fontFamily);
  static const IconData wifi = IconData(0xea900, fontFamily: _fontFamily);
  static const IconData speaker_3 = IconData(0xea901, fontFamily: _fontFamily);
  static const IconData smart_home = IconData(0xea902, fontFamily: _fontFamily);
  static const IconData music_square = IconData(0xea903, fontFamily: _fontFamily);
  static const IconData message_programming = IconData(0xea904, fontFamily: _fontFamily);
  static const IconData home_wifi = IconData(0xea905, fontFamily: _fontFamily);
  static const IconData home = IconData(0xea906, fontFamily: _fontFamily);
  static const IconData folder_cloud = IconData(0xea907, fontFamily: _fontFamily);
  static const IconData folder_2 = IconData(0xea908, fontFamily: _fontFamily);
  static const IconData emoji_happy = IconData(0xea909, fontFamily: _fontFamily);
  static const IconData electricity1 = IconData(0xea90a, fontFamily: _fontFamily);
  static const IconData document_code_2 = IconData(0xea90b, fontFamily: _fontFamily);
  static const IconData danger = IconData(0xea90c, fontFamily: _fontFamily);
  static const IconData code = IconData(0xea90d, fontFamily: _fontFamily);
  static const IconData cloud_add = IconData(0xea90e, fontFamily: _fontFamily);
  static const IconData audio_square = IconData(0xea90f, fontFamily: _fontFamily);
  static const IconData arrange_square_2 = IconData(0xea910, fontFamily: _fontFamily);
  static const IconData volume_slash = IconData(0xea911, fontFamily: _fontFamily);
  static const IconData volume_high = IconData(0xea912, fontFamily: _fontFamily);
  static const IconData flash_slash = IconData(0xea913, fontFamily: _fontFamily);
  static const IconData cpu = IconData(0xea914, fontFamily: _fontFamily);
  static const IconData chrome = IconData(0xea915, fontFamily: _fontFamily);
  static const IconData Arrow___Right_2 = IconData(0xea916, fontFamily: _fontFamily);
  static const IconData Arrow___Left_2 = IconData(0xea917, fontFamily: _fontFamily);
  static const IconData toggle_on_circle = IconData(0xea918, fontFamily: _fontFamily);
  static const IconData toggle_on = IconData(0xea919, fontFamily: _fontFamily);
  static const IconData toggle_off_circle = IconData(0xea91a, fontFamily: _fontFamily);
  static const IconData toggle_off = IconData(0xea91b, fontFamily: _fontFamily);
  static const IconData shield_tick = IconData(0xea91c, fontFamily: _fontFamily);
  static const IconData setting_3 = IconData(0xea91d, fontFamily: _fontFamily);
  static const IconData search_normal = IconData(0xea91e, fontFamily: _fontFamily);
  static const IconData ram_2 = IconData(0xea91f, fontFamily: _fontFamily);
  static const IconData main_component = IconData(0xea920, fontFamily: _fontFamily);
  static const IconData hashtag_up = IconData(0xea921, fontFamily: _fontFamily);
  static const IconData driver = IconData(0xea922, fontFamily: _fontFamily);
  static const IconData category = IconData(0xea923, fontFamily: _fontFamily);
  static const IconData bucket_square = IconData(0xea924, fontFamily: _fontFamily);
  static const IconData airpods = IconData(0xea925, fontFamily: _fontFamily);
  static const IconData volume_low = IconData(0xea926, fontFamily: _fontFamily);
  static const IconData video = IconData(0xea927, fontFamily: _fontFamily);
  static const IconData timer = IconData(0xea928, fontFamily: _fontFamily);
  static const IconData task_square = IconData(0xea929, fontFamily: _fontFamily);
  static const IconData sun = IconData(0xea92a, fontFamily: _fontFamily);
  static const IconData stop_circle = IconData(0xea92b, fontFamily: _fontFamily);
  static const IconData speaker = IconData(0xea92c, fontFamily: _fontFamily);
  static const IconData sms_star = IconData(0xea92d, fontFamily: _fontFamily);
  static const IconData sms_notification = IconData(0xea92e, fontFamily: _fontFamily);
  static const IconData sms = IconData(0xea92f, fontFamily: _fontFamily);
  static const IconData record_circle = IconData(0xea930, fontFamily: _fontFamily);
  static const IconData receive_square = IconData(0xea931, fontFamily: _fontFamily);
  static const IconData ram = IconData(0xea932, fontFamily: _fontFamily);
  static const IconData profile_tick = IconData(0xea933, fontFamily: _fontFamily);
  static const IconData printer = IconData(0xea934, fontFamily: _fontFamily);
  static const IconData previous = IconData(0xea935, fontFamily: _fontFamily);
  static const IconData play_circle = IconData(0xea936, fontFamily: _fontFamily);
  static const IconData pause_circle = IconData(0xea937, fontFamily: _fontFamily);
  static const IconData notification = IconData(0xea938, fontFamily: _fontFamily);
  static const IconData note_square1 = IconData(0xea939, fontFamily: _fontFamily);
  static const IconData note_favorite = IconData(0xea93a, fontFamily: _fontFamily);
  static const IconData next = IconData(0xea93b, fontFamily: _fontFamily);
  static const IconData mouse = IconData(0xea93c, fontFamily: _fontFamily);
  static const IconData moon1 = IconData(0xea93d, fontFamily: _fontFamily);
  static const IconData monitor = IconData(0xea93e, fontFamily: _fontFamily);
  static const IconData microphone_2 = IconData(0xea93f, fontFamily: _fontFamily);
  static const IconData microphone = IconData(0xea940, fontFamily: _fontFamily);
  static const IconData location = IconData(0xea941, fontFamily: _fontFamily);
  static const IconData key = IconData(0xea942, fontFamily: _fontFamily);
  static const IconData instagram = IconData(0xea943, fontFamily: _fontFamily);
  static const IconData home_2 = IconData(0xea944, fontFamily: _fontFamily);
  static const IconData hierarchy_square = IconData(0xea945, fontFamily: _fontFamily);
  static const IconData headphone = IconData(0xea946, fontFamily: _fontFamily);
  static const IconData forward = IconData(0xea947, fontFamily: _fontFamily);
  static const IconData flash = IconData(0xea948, fontFamily: _fontFamily);
  static const IconData driver_refresh = IconData(0xea949, fontFamily: _fontFamily);
  static const IconData cpu_setting = IconData(0xea94a, fontFamily: _fontFamily);
  static const IconData cpu_charge = IconData(0xea94b, fontFamily: _fontFamily);
  static const IconData code1 = IconData(0xea94c, fontFamily: _fontFamily);
  static const IconData cloud_sunny = IconData(0xea94d, fontFamily: _fontFamily);
  static const IconData cloud_notif = IconData(0xea94e, fontFamily: _fontFamily);
  static const IconData cloud = IconData(0xea94f, fontFamily: _fontFamily);
  static const IconData clock = IconData(0xea950, fontFamily: _fontFamily);
  static const IconData chart_2 = IconData(0xea951, fontFamily: _fontFamily);
  static const IconData category1 = IconData(0xea952, fontFamily: _fontFamily);
  static const IconData calendar_2 = IconData(0xea953, fontFamily: _fontFamily);
  static const IconData box = IconData(0xea954, fontFamily: _fontFamily);
  static const IconData bluetooth_2 = IconData(0xea955, fontFamily: _fontFamily);
  static const IconData battery = IconData(0xea956, fontFamily: _fontFamily);
  static const IconData battery_charging = IconData(0xea957, fontFamily: _fontFamily);
  static const IconData backward = IconData(0xea958, fontFamily: _fontFamily);
  static const IconData arrow_left = IconData(0xea959, fontFamily: _fontFamily);
  static const IconData activity = IconData(0xea95a, fontFamily: _fontFamily);
  static const IconData tick_circle = IconData(0xea95b, fontFamily: _fontFamily);
  static const IconData arrow_right = IconData(0xea95c, fontFamily: _fontFamily);
  static const IconData battery_10 = IconData(0xea95d, fontFamily: _fontFamily);
  static const IconData battery_50 = IconData(0xea95e, fontFamily: _fontFamily);
  static const IconData battery_full = IconData(0xea95f, fontFamily: _fontFamily);
  static const IconData battery_disable = IconData(0xea960, fontFamily: _fontFamily);
  static const IconData grid_2 = IconData(0xea961, fontFamily: _fontFamily);
  static const IconData scroll = IconData(0xea962, fontFamily: _fontFamily);
  static const IconData send = IconData(0xea963, fontFamily: _fontFamily);
}
